name: publish
on:
  push:
    tags: v*.*.*
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Action
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: Run Tests
      run: |
        flutter pub get
        flutter test
    - name: Publish
      uses: sakebook/actions-flutter-pub-publisher@v1.3.1
      with:
        credential: ${{ secrets.CREDENTIAL_JSON }}
        dry_run: false