name: Publish
on:
  push:
    tags: v*.*.*
  workflow_dispatch:
jobs:
  Publish:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: flutter pub get
    - name: Publish package
      uses: sakebook/actions-flutter-pub-publisher@v1.3.1
      with:
        credential: ${{ secrets.CREDENTIAL_JSON }}
        flutter_package: false
        dry_run: true
